int isEven(int a);
int isPrime(int a);
int gcd(int a,int b);
int lcm(int a,int b);
int power(int base,int exp);
int modExp(int base, int exp, int mod); 
int factorial(int n);
int sumDigits(int n);
int reverseNumber(int n);
int isPalindromeNumber(int n);
int sumDivisors(int n);
int isPerfectNumber(int n);
int isArmstrong(int n);
float randomNumber(int max , int min);    
int sumArray(int T[],int n);
float averageArray(int T[], int n);
int maxArray(int T[], int n);
int minArray(int T[], int n);
void sortAscending(int T[], int n); 